---
deployment_type: awx

ingress_type: none
ingress_api_version: 'networking.k8s.io/v1'
ingress_annotations: ''
ingress_class_name: ''
ingress_controller: ''

set_self_owneref: true

_control_plane_ee_image: "044063822467.dkr.ecr.ap-southeast-1.amazonaws.com/awx:awx-ee"
_image_pull_policy: Always
image_pull_secrets: []

finalizer_run: false
